line-length = 120
target-version = "py312"

include = ["aiochlite/**.py", "tests/**.py"]

[lint]
select = [
    "ALL",
]

ignore = [
    "ARG",
    "ANN",
    "B010",
    "BLE001",
    "COM812",
    "D",
    "EM101",
    "EM102",
    "FBT001",
    "ISC003",
    "N818",
    "PT001",
    "PT023",
    "PLR0913",
    "PLR2004",
    "PLC0415",
    "RET505",
    "S101",
    "S110",
    "SIM103",
    "SIM108",
    "SIM114",
    "SLF001",
    "TRY003",
    "TC001",
    "TC002",
    "TC003",
    "TC006",
    "UP041",
    "UP035",
]

[lint.per-file-ignores]
"tests/**" = ["DTZ001", "PLR2004", "S608"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

exclude = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "venv",
    "_build",
    "buck-out",
    "build",
    "docs",
    ".pytest_cache",
    ".idea",
    "__pycache__",
]
